# toml syntax highlight
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# typescript syntax highlight
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'
hook_source = '''
let g:typescript_indent_disable = 1
let g:typescript_compiler_binary = 'tsc'
let g:typescript_compiler_options = ''
'''

# html5 syntax
[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'
hook_source = '''
let g:html5_event_handler_attributes_complete = 1
let g:html5_rdfa_attributes_complete = 1
let g:html5_microdata_attributes_complete = 1
let g:html5_aria_attributes_complete = 1
'''

# js library syntax
[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
hook_source = '''
let g:used_javascript_libs = 'vue,react,flux,jquery,jasmin,angularjs,angularui,angularuirouter'
autocmd BufReadPre *.js let b:javascript_lib_use_jquery = 1
autocmd BufReadPre *.ts let b:javascript_lib_use_angularjs = 1
autocmd BufReadPre *.vue let b:javascript_lib_use_vue = 1
'''
