# 補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'roxma/nvim-yarp'
if = '''!has('nvim')'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '''!has('nvim')'''

# status line
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_source = '''
let g:airline#extensions#tabline#enabled = 1
set laststatus=2
let g:airline_theme = 'luna'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# インデント可視化
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_source = '''
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_auto_colors = 0
let g:indent_guides_guide_size = 1
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd guibg=lightgrey ctermbg=lightgrey
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=lightyellow ctermbg=lightyellow
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_source = '''
let g:quickrun_config = get(g:, 'quickrun_config', {})
let g:quickrun_config._ = {
      \ 'outputter/buffer/split'  : ':rightbelow 8sp',
      \ 'outputter/buffer/close_on_empty' : 1,
      \ }
'''

# 行末スペース可視化
[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
hook_source = '''
let g:better_whitespace_enabled=1
let g:strip_whitespace_on_save=1
'''

# コメントアウト
[[plugins]]
repo = 'tomtom/tcomment_vim'

# sytastic
# @see https://tackeyy.com/blog/posts/introduction-of-vim-syntastic
[[plugins]]
repo = 'scrooloose/syntastic'
hook_source = '''
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 0
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let g:syntastic_mode_map = { 'mode': 'active', 'active_filetypes': ['ruby'] }
let g:syntastic_ruby_checkers = ['rubocop']
let g:syntastic_ruby_rubocop_exe = 'bundle exec rubocop'

let g:syntastic_error_symbol='✗'
let g:syntastic_style_error_symbol = '✗'
let g:syntastic_warning_symbol = '⚠'
let g:syntastic_style_warning_symbol = '⚠'
'''

